### ISSUE TITLE
RepayFromLadle and closeFromLadle send the collateral and remainder to the same address

### ISSUE THREAD

**Issue by alcueca** [yieldprotocol/bugs#1]
repayFromLadle and closeFromLadle send the collateral and remainder to the same address, which means that they cannot be chained with other actions afterwards.

From the user point of view, if:
 - They add liquidity
 - Remove it before the pool they initially provided to reaches maturity
 - They have made a profit, or the interest rates rise significantly
 - They used "Borrow and Pool"
Then they will receive some fyToken instead of underlying.

RepayFromLadle and closeFromLadle should be refactored to take an address for each token transfer.

This can be coded as a new Ladle, first used as a module in the existing Ladle, and eventually promoted to main Ladle. Or we can do a complete swap.

**Comment by alcueca** [comment]
Let's fix this with a Ladle module. @Sabnock01, could you please take care of it?

**Comment by Sabnock01** [comment]
[Ladle module](https://github.com/yieldprotocol/vault-v2/pull/486)
